// app/layout.server.js
import localFont from "next/font/local";
import RootLayout from "./layout.client";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <RootLayout geistSans={geistSans} geistMono={geistMono}>
      {children}
    </RootLayout>
  );
}
