// import localFont from "next/font/local";
// import "@/app/globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`  antialiased max-w-[100vw] overflow-x-hidden`}>
                <div className="max-w-screen mx-auto overflow-hidden">
                    {children}
                </div>
            </body>
        </html>
    );
}
